# .github/workflows/develop.yml
name: Develop Branch CI

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]

jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  extensions: mbstring, intl, xml, pgsql, pdo_pgsql
                  coverage: none

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '23'
                  cache: 'yarn'

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Install PHP dependencies
              run: composer install --prefer-dist --no-progress

            - name: Install JS dependencies
              run: yarn install

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse

            - name: Run ESLint
              run: yarn lint
